# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:  
- task: PowerShell@2
  displayName: Build
  inputs:
    targetType: 'inline'
    script: |
      docker build -t productapi:latest .
    workingDirectory: '$(Build.SourcesDirectory)'
  
- task: PowerShell@2
  displayName: Tag
  inputs:
    targetType: 'inline'
    script: |
      docker tag productapi:latest sanjaybpatel/productapi:latest
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PowerShell@2
  displayName: Log-in                   	# for ACR password will be Access key
  inputs:
    targetType: 'inline'
    script: |
      docker login -u sanjaybpatel -p SanjayPatel@123			
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PowerShell@2
  displayName: Push
  inputs:
    targetType: 'inline'
    script: |
      docker push sanjaybpatel/productapi:latest
    workingDirectory: '$(Build.SourcesDirectory)'

- task: PowerShell@2
  displayName: 'Deploy to OpenShift'
  inputs:
    targetType: 'inline'
    script: |
      oc login --token=sha256~X3ZcWMJcqXSoln6N5FaLLzlHyDW4gO7WWKH524_hCYg --server=https://api.sandbox-m3.1530.p1.openshiftapps.com:6443
      oc project sanjay-b-patel-dev
      oc new-app myapp
      oc expose service myapp
    workingDirectory: '$(Build.SourcesDirectory)'

